
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

cruise:
    resource: "@CruiseBundle/Controller/"
    type:     annotation
    prefix:   /

