<?php

namespace CruiseBundle\Repository;

/**
 * PriceDefaultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceDefaultRepository extends \Doctrine\ORM\EntityRepository
{
}
