<?php

namespace CruiseBundle\Repository;

/**
 * RoundTripRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoundTripRepository extends \Doctrine\ORM\EntityRepository
{
}
